name: Deploy Snowflake Infra + dbt

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Snowflake CLI
        run: pip install snowflake-cli-labs

      - name: Install dbt
        run: pip install dbt-snowflake

      - name: Configure Snowflake Connection
        run: |
          snow connection add \
            --connection-name github \
            --account $SNOWFLAKE_ACCOUNT \
            --user $SNOWFLAKE_USER \
            --password $SNOWFLAKE_PASSWORD \
            --role ACCOUNTADMIN \
            --warehouse wh_etl \
            --database retail_prod \
            --schema bronze \
            --no-interactive
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}

      - name: Deploy Warehouses
        run: snow sql -c github -f snowflake/infra/01_warehouses.sql

      - name: Deploy Database
        run: snow sql -c github -f snowflake/infra/02_database.sql

      - name: Deploy Schemas
        run: snow sql -c github -f snowflake/infra/03_schemas.sql

      - name: Deploy Bronze Table
        run: snow sql -c github -f snowflake/bronze/01_transactions_raw.sql

      - name: Deploy Stage
        run: snow sql -c github -f snowflake/stages/01_internal_stage.sql

      # ---------------------------
      # DBT SECTION STARTS HERE
      # ---------------------------

      - name: Create dbt Profile
        run: |
          mkdir -p ~/.dbt
          cat <<EOF > ~/.dbt/profiles.yml
          retail_profile:
            target: prod
            outputs:
              prod:
                type: snowflake
                account: ${SNOWFLAKE_ACCOUNT}
                user: ${SNOWFLAKE_USER}
                password: ${SNOWFLAKE_PASSWORD}
                role: ACCOUNTADMIN
                warehouse: wh_etl
                database: retail_prod
                schema: silver
          EOF
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}

      - name: Run dbt
        run: |
          cd dbt
          dbt run
