name: Deploy Snowflake + dbt + BI Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Snowflake CLI
        run: pip install snowflake-cli-labs

      - name: Install dbt
        run: pip install dbt-snowflake

      # ------------------------------------------------
      # Configure Snowflake Connection
      # ------------------------------------------------
      - name: Configure Snowflake Connection
        run: |
          snow connection add \
            --connection-name github \
            --account $SNOWFLAKE_ACCOUNT \
            --user $SNOWFLAKE_USER \
            --password $SNOWFLAKE_PASSWORD \
            --role ACCOUNTADMIN \
            --warehouse wh_etl \
            --database retail_prod \
            --schema bronze \
            --no-interactive
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}

      # ------------------------------------------------
      # Deploy Infra
      # ------------------------------------------------
      - name: Deploy Warehouses
        run: snow sql -c github -f snowflake/infra/01_warehouses.sql

      - name: Deploy Database
        run: snow sql -c github -f snowflake/infra/02_database.sql

      - name: Deploy Schemas
        run: snow sql -c github -f snowflake/infra/03_schemas.sql

      - name: Deploy Bronze Table
        run: snow sql -c github -f snowflake/bronze/01_transactions_raw.sql

      - name: Deploy Stage
        run: snow sql -c github -f snowflake/stages/01_internal_stage.sql

      # ------------------------------------------------
      # Upload CSV to Stage
      # ------------------------------------------------
      - name: Upload CSV to Stage
        run: |
          snow stage copy -c github data/retail_transactions.csv \
            @retail_prod.bronze.retail_stage

      # ------------------------------------------------
      # Load Bronze Table
      # ------------------------------------------------
      - name: Copy Into Bronze
        run: |
          snow sql -c github -q "
          COPY INTO retail_prod.bronze.transactions_raw
          FROM @retail_prod.bronze.retail_stage/retail_transactions.csv
          FILE_FORMAT = (
            TYPE = CSV
            SKIP_HEADER = 1
            FIELD_OPTIONALLY_ENCLOSED_BY='\"'
          );
          "

      # ------------------------------------------------
      # Create dbt Profile
      # ------------------------------------------------
      - name: Create dbt Profile
        run: |
          mkdir -p ~/.dbt
          cat <<EOF > ~/.dbt/profiles.yml
          retail_profile:
            target: prod
            outputs:
              prod:
                type: snowflake
                account: ${SNOWFLAKE_ACCOUNT}
                user: ${SNOWFLAKE_USER}
                password: ${SNOWFLAKE_PASSWORD}
                role: ACCOUNTADMIN
                warehouse: wh_etl
                database: retail_prod
                schema: public
          EOF
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}

      # ------------------------------------------------
      # Run dbt (Silver + Gold)
      # ------------------------------------------------
      - name: Run dbt
        run: |
          cd dbt
          dbt run

      # ------------------------------------------------
      # Deploy BI Views (Acts like BI Worksheet)
      # ------------------------------------------------
      - name: Deploy BI Schema
        run: snow sql -c github -f bi/01_create_schema.sql

      - name: Deploy KPI View
        run: snow sql -c github -f bi/02_kpi_summary.sql

      - name: Deploy Product Performance View
        run: snow sql -c github -f bi/03_product_performance.sql

      - name: Deploy Revenue Trend View
        run: snow sql -c github -f bi/04_revenue_trend.sql

     # - name: Deploy Customer Contribution View
     #   run: snow sql -c github -f bi/05_customer_contribution.sql
